# ---- Build Stage ----
FROM node:24.10.0-alpine AS builder

WORKDIR /app

COPY package.json */package-lock.json* ./

RUN npm install

COPY . .

RUN npm run build

# ---- Production Stage ----
FROM node:24.10.0-alpine

WORKDIR /app

COPY package.json */package-lock.json* ./

RUN npm install --only=production

COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["node", "dist/server.js"]